spring.application.name=purchaseOrder
server.port=8081
server.

# H2 database configuration
spring.datasource.url=jdbc:h2:file:./data/orderDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=adminOrder
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# External API configuration
inventory.api.base-url=http://localhost:8080/inventory

# Kafka configurations
spring.kafka.bootstrap-servers=pkc-w8nyg.me-central1.gcp.confluent.cloud:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
springboot.purchase.order.topic=customer-orders
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='BWJO7DDFMJEUQQXP' password='MeIATKLb6l+st8hnCZq1pmuy2//VMFYqZMlmC66iZSLbT/h+KXF952goOB5R35ej';
spring.kafka.client-id=ccloud-java-client-ae9ca0fb-1fd3-464c-970d-3986b78b9d28
spring.kafka.session.timeout.ms=45000



# Show SQL in console (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 web console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console